/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bots.Vista;

import com.mycompany.bots.Logica.Bot;

import javax.swing.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 * @author ing Juan Mata
 */
public class Principal extends javax.swing.JFrame {

    ArrayList<Bot> bots = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBots;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbFras;
    private javax.swing.JLabel lbNom;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextArea txtFras;
    private javax.swing.JTextField txtMensaje;
    private javax.swing.JTextField txtNomBot;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        iniciar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //Create and display the form
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    /**
     * Comienza los listeners y eventos del programa
     */
    private void iniciar() {
        btnSave.addActionListener(e -> crear());
        comboBots.addActionListener(e -> encender());
        txtMensaje.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                Bot bot = bots.get(comboBots.getSelectedIndex() - 1);
                if (e.getKeyChar() == KeyEvent.VK_ENTER) {
                    if (bot.getNombreUsuario().equals("")) {
                        txtChat.setText(txtChat.getText() + "\n" + bot.nombrarUsuario(txtMensaje.getText()));
                        limpiarEntradas();
                    } else {
                        txtChat.setText(txtChat.getText() + "\n" + txtMensaje.getText() + "\n" + bot.hablar(txtMensaje.getText()));
                        limpiarEntradas();
                    }
                }
            }
        });
    }

    /**
     * Da inicio al bot seleccionado
     */
    private void encender() {
        if (comboBots.getSelectedIndex() > 0) {
            Bot actual = bots.get(comboBots.getSelectedIndex() - 1);
            txtChat.setText(actual.encender());
            txtMensaje.setEditable(true);
        } else {
            txtMensaje.setEditable(false);
        }
    }

    private void crear() {
        String[] respuestas = txtFras.getText().split("\n");

        if (!txtNomBot.getText().equals("")) {
            bots.add(new Bot(respuestas, txtNomBot.getText()));
            comboBots.addItem(txtNomBot.getText());
            limpiarEntradas();
        } else
            JOptionPane.showMessageDialog(this, "Debe de colocar un nombre al bot", "Alerta nombre",
                    JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Limpia los campos de los datos del bot
     */
    private void limpiarEntradas() {
        txtNomBot.setText("");
        txtFras.setText("");
        txtMensaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNom = new javax.swing.JLabel();
        lbFras = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFras = new javax.swing.JTextArea();
        txtNomBot = new javax.swing.JTextField();
        txtMensaje = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBots = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNom.setText("Nombre del robot: ");

        lbFras.setText("Introducir una respuesta por renglon");

        txtFras.setColumns(20);
        txtFras.setRows(5);
        jScrollPane2.setViewportView(txtFras);

        txtMensaje.setEditable(false);

        txtChat.setEditable(false);
        txtChat.setColumns(20);
        txtChat.setRows(5);
        jScrollPane3.setViewportView(txtChat);

        jLabel1.setText("chat con: ");

        jLabel2.setText("Bots: ");

        comboBots.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Seleccione un bot"}));

        btnSave.setText("Guardar bot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(19, 19, 19).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(layout.createSequentialGroup().addComponent(lbNom).addGap(18, 18, 18).addComponent(txtNomBot)).addComponent(lbFras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(txtMensaje).addComponent(jScrollPane3).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(layout.createSequentialGroup().addComponent(jLabel2).addGap(18, 18, 18).addComponent(comboBots, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(38, 38, 38).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lbNom).addComponent(txtNomBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel2).addComponent(comboBots, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(43, 43, 43).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lbFras).addComponent(jLabel1)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout.createSequentialGroup().addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE).addGap(18, 18, 18).addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jScrollPane2).addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(btnSave))).addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

}
